### ISSUE TITLE
System.StackOverflowException

### ISSUE THREAD

**Issue by Helian-faure** [Shane32/EPPlus#7]
Hello,
since the installation of the KB5011048 an exception is raised when accessing the Workbook of an XlsPackage created using a template file like this:
            // Create a new xlsx file
            xlPackage = new ExcelPackage(xlFile, xlTemplateFile);

            // Get worksheet of usage
            xlWorksheetParams = xlPackage.Workbook.Worksheets[C_ParamSheet];
 
![2022-12-18_20h11_15](https://user-images.githubusercontent.com/65974272/208315108-96db5746-c3e2-4435-a44d-65d0b797813f.png)

**Comment by Shane32** [comment]
Can you provide sample files to replicate the problem?

**Comment by Shane32** [comment]
Added tests for .NET Framework 4.8.1 in #18 .  Please comment if you can provide code/files to replicate the issue.
